//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Vaishnavi\Solution_AutoHoleInspector\HoleSelectionUI.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: HP
//              Version: NX 2306
//              Date: 12-29-2025  (Format: mm-dd-yyyy)
//              Time: 13:48 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.Features;
using NXOpen.UF;
using System;
using System.Diagnostics;
using System.IO;
using ProgressBar;
using Excel = Microsoft.Office.Interop.Excel;



//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class HoleSelectionUI
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;
    private NXOpen.BlockStyler.SelectObject holeOneID;
    private NXOpen.BlockStyler.SelectObject holeTwoID;
    private NXOpen.BlockStyler.SpecifyCSYS csysID;
    private NXOpen.BlockStyler.Group group;// Block type: Group
    private NXOpen.BlockStyler.FolderSelection folderSelectionID;// Block type: NativeFolderBrowser
    private NXOpen.BlockStyler.Button executeID;
    private bool executePressed = false;

    private static UFSession theUfSession = UFSession.GetUFSession();



    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesEnabled_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesEnabled_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesEnabled_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesEnabled_TwocurveIntersection = (1 << 13);
    public static readonly int SnapPointTypesEnabled_TangentPoint = (1 << 14);
    public static readonly int SnapPointTypesEnabled_Poles = (1 << 15);
    public static readonly int SnapPointTypesEnabled_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesEnabled_FacetVertexPoint = (1 << 17);
    public static readonly int SnapPointTypesEnabled_DefiningPoint = (1 << 18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesOnByDefault_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesOnByDefault_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesOnByDefault_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesOnByDefault_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesOnByDefault_FacetVertexPoint = (1 << 17);

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public HoleSelectionUI()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "HoleSelectionUI.dlx";
            theDialog = theUI.CreateDialog(System.IO.Path.Combine(AppContext.BaseDirectory, theDlxFileName));
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            //theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        //PartSelection partDlg = null;
        HoleSelectionUI holeDlg = null;

        try
        {
            //partDlg = new PartSelection();
            //NXOpen.BlockStyler.BlockDialog.DialogResponse resp =
            //    partDlg.Launch();

            //partDlg.Dispose();
            //partDlg = null;


            //if (resp != NXOpen.BlockStyler.BlockDialog.DialogResponse.Ok)
            //    return;


            holeDlg = new HoleSelectionUI();
            holeDlg.Launch();
        }
        catch (Exception ex)
        {
            UI.GetUI().NXMessageBox.Show(
                "Launcher Error",
                NXMessageBox.DialogType.Error,
                ex.ToString()
            );
        }
        finally
        {
            if (holeDlg != null)
                holeDlg.Dispose();
        }
    }

    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
    public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }

    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
            GetUnloadOption(arg);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }

    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            holeOneID = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("holeOneID");
            holeTwoID = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("holeTwoID");
            csysID = (SpecifyCSYS)theDialog.TopBlock.FindBlock("csysID");
            group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
            folderSelectionID = (NXOpen.BlockStyler.FolderSelection)theDialog.TopBlock.FindBlock("folderSelectionID");
            executeID = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("executeID");

            // FILTER FOR DATUM HOLE 1
            holeOneID.ClearFilter();

            NXOpen.Selection.MaskTriple circularEdgeMask =
                new NXOpen.Selection.MaskTriple(
                    UFConstants.UF_solid_type,
                    0,
                    UFConstants.UF_UI_SEL_FEATURE_CIRCULAR_EDGE
                );

            holeOneID.SetSelectionFilter(
                NXOpen.Selection.SelectionAction.ClearAndEnableSpecific,
                new NXOpen.Selection.MaskTriple[] { circularEdgeMask }
            );

            holeOneID.MaximumScopeAsString = "Entire Assembly";


            // FILTER FOR DATUM HOLE 2
            holeTwoID.ClearFilter();

            holeTwoID.SetSelectionFilter(
                NXOpen.Selection.SelectionAction.ClearAndEnableSpecific,
                new NXOpen.Selection.MaskTriple[] { circularEdgeMask }
            );

            holeTwoID.MaximumScopeAsString = "Entire Assembly";
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString()
            );
        }
    }


    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set
    //here will take precedence and dialog will be launched showing that value.
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if (block == holeOneID)
            {
                //---------Enter your code here-----------
            }
            else if (block == holeTwoID)
            {
                //---------Enter your code here-----------
            }
            else if (block == csysID)
            {
                //---------Enter your code here-----------
            }
            else if (block == folderSelectionID)
            {
                //---------Enter your code here-----------
            }
            else if (block == executeID)
            {
                if (string.IsNullOrEmpty(folderSelectionID.Path))
                {
                    theUI.NXMessageBox.Show(
                        "Error",
                        NXMessageBox.DialogType.Error,
                        "Please select report location."
                    );
                    return 0;
                }


               executePressed = true;
               ExecuteMeasurementLogic();
                return 0;
            }


        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    //public int ok_cb()
    //{
    //    try
    //    {
    //        Edge hole1 = GetSelectedHoleEdge(holeOneID, "Datum Hole 1");
    //        Edge hole2 = GetSelectedHoleEdge(holeTwoID, "Datum Hole 2");

    //        double dia1 = GetDiameterFromCircularEdge(hole1);
    //        double dia2 = GetDiameterFromCircularEdge(hole2);

    //        CartesianCoordinateSystem carCsys = GetUserDefinedCsys();

    //        Point3d c1 = GetHoleCenterFromEdge(hole1);
    //        Point3d c2 = GetHoleCenterFromEdge(hole2);

    //        Vector3d pDir = new Vector3d(0.0, 1.0, 0.0);
    //        double pitch = GetPitchAlongAxis(c1, c2, pDir);

    //        DatumCsys h1Csys = CreateHoleDatumCsys(c1);
    //        DatumCsys h2Csys = CreateHoleDatumCsys(c2);

    //        double ref_h1 = ToNxAlternatePlaneAngle(
    //            AngleBetweenYZPlanes(carCsys, h1Csys.GetEntities()[0] as CartesianCoordinateSystem));

    //        double ref_h2 = ToNxAlternatePlaneAngle(
    //            AngleBetweenYZPlanes(carCsys, h2Csys.GetEntities()[0] as CartesianCoordinateSystem));

    //        double h1_h2 = AngleBetweenYZPlanes(
    //            h1Csys.GetEntities()[0] as CartesianCoordinateSystem,
    //            h2Csys.GetEntities()[0] as CartesianCoordinateSystem);

    //        if (executePressed)
    //        {
    //            string csvPath = Path.Combine(folderSelectionID.Path, "AutoHoleInspector_Report.csv");

    //            //START PROGRESS BAR 
    //            ProgressController.StartProgressBar(
    //                stepSize: 10,
    //                interval: 0.15,
    //                timerStatus: true,
    //                progressLabel: "Creating Excel Report..."
    //            );

    //            for (int i = 0; i < 5; i++)
    //            {
    //                ProgressController.IncrementProgressBar();
    //                System.Threading.Thread.Sleep(150);
    //            }

    //            int partSerial = GetNextPartSerial(csvPath);

    //            CreateCsvReport(
    //                partSerial,
    //                dia1, dia2,
    //                ref_h1, ref_h2,
    //                h1_h2,
    //                pitch,
    //                c1, c2,
    //                csvPath
    //            );

    //            for (int i = 0; i < 5; i++)
    //            {
    //                ProgressController.IncrementProgressBar();
    //                System.Threading.Thread.Sleep(150);
    //            }

    //            ProgressController.StopProgressBar();

    //            //SUCCESS MESSAGE 
    //            theUI.NXMessageBox.Show(
    //                "Success",
    //                NXMessageBox.DialogType.Information,
    //                "Modeling Check List Created Successfully"
    //            );

    //            //OPEN EXCEL AFTER OK
    //            if (File.Exists(csvPath))
    //            {
    //                Process.Start(new ProcessStartInfo
    //                {
    //                    FileName = csvPath,
    //                    UseShellExecute = true
    //                });
    //            }
    //        }

    //        return 0;
    //    }
    //    catch (Exception ex)
    //    {
    //        theUI.NXMessageBox.Show(
    //            "Hole Selection Error",
    //            NXMessageBox.DialogType.Error,
    //            ex.Message
    //        );
    //        return 1;
    //    }
    //}

private void ExecuteMeasurementLogic()
 {
        Edge hole1 = GetSelectedHoleEdge(holeOneID, "Datum Hole 1");
        Edge hole2 = GetSelectedHoleEdge(holeTwoID, "Datum Hole 2");

        double dia1 = GetDiameterFromCircularEdge(hole1);
        double dia2 = GetDiameterFromCircularEdge(hole2);

        CartesianCoordinateSystem carCsys = GetUserDefinedCsys();

        Point3d c1 = GetHoleCenterFromEdge(hole1);
        Point3d c2 = GetHoleCenterFromEdge(hole2);

        Vector3d pDir = new Vector3d(0.0, 1.0, 0.0);
        double pitch = GetPitchAlongAxis(c1, c2, pDir);

        DatumCsys h1Csys = CreateHoleDatumCsys(c1);
        DatumCsys h2Csys = CreateHoleDatumCsys(c2);

        double ref_h1 = ToNxAlternatePlaneAngle(
            AngleBetweenYZPlanes(carCsys, h1Csys.GetEntities()[0] as CartesianCoordinateSystem));

        double ref_h2 = ToNxAlternatePlaneAngle(
            AngleBetweenYZPlanes(carCsys, h2Csys.GetEntities()[0] as CartesianCoordinateSystem));

        double h1_h2 = AngleBetweenYZPlanes(
            h1Csys.GetEntities()[0] as CartesianCoordinateSystem,
            h2Csys.GetEntities()[0] as CartesianCoordinateSystem);

        string folderPath = folderSelectionID.Path;
        if (executePressed)
        {

            ProgressController.StartProgressBar(
                stepSize: 10,
                interval: 0.15,
                timerStatus: true,
                progressLabel: "Creating Excel Report..."
            );
        }
        // System.Threading.Thread.Sleep(150);
        for (int i = 0; i < 5; i++)
        {
            ProgressController.IncrementProgressBar();
            System.Threading.Thread.Sleep(150);
        }

        //int partSerial = GetNextPartSerial(csvPath);

       string excelPath= CreateExcelReport(
                dia1, dia2,
                ref_h1, ref_h2,
                h1_h2,
                pitch,
                c1, c2,
                folderPath
            );

        for (int i = 0; i < 5; i++)
        {
            ProgressController.IncrementProgressBar();
            System.Threading.Thread.Sleep(150);
        }

        ProgressController.StopProgressBar();

            //SUCCESS MESSAGE 
            theUI.NXMessageBox.Show(
                "Success",
                NXMessageBox.DialogType.Information,
                "Modeling Check List Created Successfully"
            );

            //OPEN EXCEL AFTER OK
            if (File.Exists(excelPath))
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = excelPath,
                    UseShellExecute = true
                });
            }
        }

private double CleanZero(double value, double tol = 1e-5)
  {
        return Math.Abs(value) < tol ? 0.0 : value;
  }

private string  CreateExcelReport(
        double dia1, double dia2,
        double carAngle1, double carAngle2,
        double mutualAngle,
        double pitch,
        Point3d c1, Point3d c2,
        string folderPath)
{
    Excel.Application excel = new Excel.Application();
    excel.Visible = false;

    Excel.Workbook wb = excel.Workbooks.Add();
    Excel.Worksheet ws = wb.ActiveSheet;
    ws.Name = "Inspection Report";

    //HEADER
    ws.Cells[1, 1] = "Sr.NO";
    ws.Cells[1, 2] = "PART NUMBER";
    ws.Cells[1, 3] = "REVISION\nNO";
    ws.Cells[1, 4] = "PICTORIAL\nVIEW";
    ws.Cells[1, 5] = "HOLE";
    ws.Cells[1, 6] = "DIA";
    ws.Cells[1, 7] = "ANGLE WITH\nCAR LINE";
    ws.Cells[1, 8] = "ANGLE WITH\nEACH OTHER";
    ws.Cells[1, 9] = "PITCH";
    ws.Cells[1, 10] = "X";
    ws.Cells[1, 11] = "Y";
    ws.Cells[1, 12] = "Z";
    ws.Cells[1, 13] = "DATUM STATUS";

    Excel.Range header = ws.Range["A1:M1"];
    header.Font.Bold = true;
    header.WrapText = true;
    header.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
    header.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;
    header.Borders.LineStyle = Excel.XlLineStyle.xlContinuous;
    ws.Rows[1].RowHeight = 35;


    int row = 2;
    int srNo = 1;

         ws.Cells[row, 5] = "D1";
         ws.Cells[row, 6] = dia1;
         ws.Cells[row, 7] = carAngle1;
         ws.Cells[row, 8] = mutualAngle;
         ws.Cells[row, 9] = pitch;
         ws.Cells[row, 10] = c1.X;
         ws.Cells[row, 11] = c1.Y;
         ws.Cells[row, 12] = c1.Z;


       

        ws.Cells[row + 1, 5] = "D2";
        ws.Cells[row + 1, 6] = dia2;
        ws.Cells[row + 1, 7] = carAngle2;
        ws.Cells[row + 1, 10] = CleanZero(c2.X); 
        ws.Cells[row + 1, 11] = CleanZero(c2.Y); 
        ws.Cells[row + 1, 12] = CleanZero(c2.Z);

        Excel.Range srRange = ws.Range[$"A{row}:A{row + 1}"];
        srRange.Merge();
        srRange.Value = srNo;
        srRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        srRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;

        Excel.Range partRange = ws.Range[$"B{row}:B{row + 1}"];
        partRange.Merge();
        partRange.Value = "";   // fill later if needed
        partRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        partRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;

        Excel.Range revRange = ws.Range[$"C{row}:C{row + 1}"];
        revRange.Merge();
        revRange.Value = "";
        revRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        revRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;

        Excel.Range picRange = ws.Range[$"D{row}:D{row + 1}"];
        picRange.Merge();
        picRange.Value = "";   // later you can insert image here
        picRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        picRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;

        Excel.Range angleRange = ws.Range[$"H{row}:H{row + 1}"];
        angleRange.Merge();
        angleRange.Value = mutualAngle;
        angleRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        angleRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;

        
        Excel.Range pitchRange = ws.Range[$"I{row}:I{row + 1}"];
        pitchRange.Merge();
        pitchRange.Value = pitch;
        pitchRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        pitchRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;


        Excel.Range statusRange = ws.Range[$"M{row}:M{row + 1}"];
        statusRange.Merge();
        statusRange.Value = "";   // later you can write datum status
        statusRange.HorizontalAlignment = Excel.XlHAlign.xlHAlignCenter;
        statusRange.VerticalAlignment = Excel.XlVAlign.xlVAlignCenter;
        statusRange.WrapText = true;


        ws.Range[$"A{row}:M{row + 1}"].Borders.LineStyle = Excel.XlLineStyle.xlContinuous;

        ws.Columns.AutoFit();

        string path = Path.Combine(folderPath, "HoleInspection.xlsx");


        excel.DisplayAlerts = false;
        wb.SaveAs(path);
        excel.DisplayAlerts = true;

        wb.Close();
        excel.Quit();

        return path;
}
private double ToNxAlternatePlaneAngle(double angle360)
    {
        // Normalize
        angle360 = angle360 % 360.0;
        if (angle360 < 0)
            angle360 += 360.0;

        // Convert to 0–180
        if (angle360 > 180.0)
            angle360 = 360.0 - angle360;

        // Prefer obtuse angle 
        if (angle360 < 90.0)
            angle360 = 180.0 - angle360;

        return angle360;
    }

private Vector3d GetYZPlaneNormal(CartesianCoordinateSystem csys)
 {
        Matrix3x3 m = csys.Orientation.Element;

        // X-axis is normal of YZ plane
        Vector3d xDir = new Vector3d(m.Xx, m.Xy, m.Xz);
        return Normalize(xDir);
 }

private double AngleBetweenYZPlanes(
    CartesianCoordinateSystem refCsys,
    CartesianCoordinateSystem targetCsys)
{
        // X axis = normal of YZ plane
        Vector3d nRef = GetYZPlaneNormal(refCsys);
        Vector3d nTar = GetYZPlaneNormal(targetCsys);


        double dot =
            nRef.X * nTar.X +
            nRef.Y * nTar.Y +
            nRef.Z * nTar.Z;

        dot = Math.Max(-1.0, Math.Min(1.0, dot));

        double angle = Math.Acos(dot) * 180.0 / Math.PI; // acute

        // Cross direction
        Vector3d cross = new Vector3d(
            nRef.Y * nTar.Z - nRef.Z * nTar.Y,
            nRef.Z * nTar.X - nRef.X * nTar.Z,
            nRef.X * nTar.Y - nRef.Y * nTar.X
        );

        // Use reference Z-axis to decide sign
        Matrix3x3 m = refCsys.Orientation.Element;
        Vector3d refZ = new Vector3d(m.Zx, m.Zy, m.Zz);

        double sign =
            cross.X * refZ.X +
            cross.Y * refZ.Y +
            cross.Z * refZ.Z;

        if (sign < 0)
            angle = 360.0 - angle;

        return angle;
    }

 
private DatumCsys CreateHoleDatumCsys(Point3d origin)
  {
        Part workPart = theSession.Parts.Work;

        CartesianCoordinateSystem refCsys =
            workPart.WCS.CoordinateSystem;

        Matrix3x3 m = refCsys.Orientation.Element;

        Vector3d xDir = new Vector3d(m.Xx, m.Xy, m.Xz);
        Vector3d yDir = new Vector3d(m.Yx, m.Yy, m.Yz);

        Xform xform = workPart.Xforms.CreateXform(
            origin,
            xDir,
            yDir,
            SmartObject.UpdateOption.WithinModeling,
            1.0
        );

        CartesianCoordinateSystem cartCsys =
            workPart.CoordinateSystems.CreateCoordinateSystem(
                xform,
                SmartObject.UpdateOption.WithinModeling
            );

        DatumCsysBuilder builder =
            workPart.Features.CreateDatumCsysBuilder(null);

        builder.Csys = cartCsys;
        builder.DisplayScaleFactor = 1.0;

        DatumCsys datumCsys =
            (DatumCsys)builder.Commit();

        builder.Destroy();
        return datumCsys;
  }



private CartesianCoordinateSystem GetUserDefinedCsys()
  {
        TaggedObject[] selected = csysID.GetSelectedObjects();

        if (selected == null || selected.Length == 0)
            throw new Exception("Please select or define CAR line CSYS.");

        //User picked a Datum CSYS
        DatumCsys datum = selected[0] as DatumCsys;
        if (datum != null)
        {
            return datum.GetEntities()[0] as CartesianCoordinateSystem;
        }

        //User picked an existing CSYS directly
        CartesianCoordinateSystem csys = selected[0] as CartesianCoordinateSystem;
        if (csys != null)
        {
            return csys;
        }

        throw new Exception("Selected object is not a valid CSYS.");
 }

private Vector3d Normalize(Vector3d v)
  {
        double mag = Math.Sqrt(v.X * v.X + v.Y * v.Y + v.Z * v.Z);
        return new Vector3d(v.X / mag, v.Y / mag, v.Z / mag);
  }


private Edge GetSelectedHoleEdge(NXOpen.BlockStyler.SelectObject holeBlock, string holeName)

  {
        TaggedObject[] selectedObjects = holeBlock.GetSelectedObjects();

        if (selectedObjects == null || selectedObjects.Length == 0)
            throw new Exception($"Please select {holeName}.");

        Edge edge = selectedObjects[0] as Edge;

        if (edge == null)
            throw new Exception($"{holeName} is not a circular edge.");

        return edge;
  }

    //Finding Diameter
private double GetDiameterFromCircularEdge(Edge edge)
  {
        Part workPart = theSession.Parts.Work;

        Unit mmUnit = workPart.UnitCollection.FindObject("MilliMeter") as Unit;

        NXObject[] sellist = new NXObject[] { edge };

        bool isApproximate;
        double arcLength;
        double radius;
        double diameter;
        double minRadius;
        Point3d startPoint;
        Point3d endPoint;
        Point3d arcCenter;

        theSession.Measurement.GetArcAndCurveProperties(
            sellist,
            mmUnit,
            true,
            out isApproximate,
            out arcLength,
            out radius,
            out diameter,
            out minRadius,
            out startPoint,
            out endPoint,
            out arcCenter
        );

        return diameter;
  }

    //Finding Pitch Distance

private double GetPitchAlongAxis(Point3d c1, Point3d c2, Vector3d axis)
  {
        double mag = Math.Sqrt(axis.X * axis.X + axis.Y * axis.Y + axis.Z * axis.Z);
        Vector3d unit = new Vector3d(axis.X / mag, axis.Y / mag, axis.Z / mag);

        Vector3d diff = new Vector3d(
            c2.X - c1.X,
            c2.Y - c1.Y,
            c2.Z - c1.Z
        );

        return Math.Abs(
            diff.X * unit.X +
            diff.Y * unit.Y +
            diff.Z * unit.Z
        );
  }



private Point3d GetHoleCenterFromEdge(Edge edge)
  {
        Part workPart = theSession.Parts.Work;
        Unit mmUnit = workPart.UnitCollection.FindObject("MilliMeter") as Unit;

        NXObject[] sel = new NXObject[] { edge };

        bool isApproximate;
        double arcLength;
        double radius;
        double diameter;
        double minRadius;
        Point3d startPoint;
        Point3d endPoint;
        Point3d arcCenter;

        theSession.Measurement.GetArcAndCurveProperties(
            sel,
            mmUnit,
            true,
            out isApproximate,
            out arcLength,
            out radius,
            out diameter,
            out minRadius,
            out startPoint,
            out endPoint,
            out arcCenter
        );

        return arcCenter;
  }

    
    //private int GetNextPartSerial(string csvPath)
    //{
    //    if (!File.Exists(csvPath))
    //        return 1;

    //    int lastSerial = 0;
    //    foreach (var line in File.ReadAllLines(csvPath))
    //    {
    //        var cols = line.Split(',');
    //        if (cols.Length > 0 && int.TryParse(cols[0], out int s))
    //            lastSerial = Math.Max(lastSerial, s);
    //    }
    //    return lastSerial + 1;
    //}

    //private void CreateCsvReport(
    // int partSerialNo,
    // double dia1, double dia2,
    // double carAngle1, double carAngle2,
    // double mutualAngle,
    // double pitch,
    // Point3d c1, Point3d c2,
    // string csvPath)
    //{
    //    bool fileExists = File.Exists(csvPath);

    //    using (StreamWriter sw = new StreamWriter(csvPath, true))
    //    {
    //        //HEADER
    //        if (!fileExists)
    //        {
    //            sw.WriteLine(
    //                "S.No,PART NUMBER,REVISION NO,PICTORIAL VIEW," +
    //                "HOLE,DIA,ANGLE WITH CAR LINE,ANGLE WITH EACH OTHER," +
    //                "PITCH,X,Y,Z,DATUM STATUS"
    //            );
    //        }

    //        // D1
    //        sw.WriteLine(
    //            $"{partSerialNo},,,," +
    //            $"D1,{dia1:F3}," +
    //            $"{carAngle1:F3}," +
    //            $"{mutualAngle:F3}," +
    //            $"{pitch:F3}," +
    //            $"{c1.X:F3},{c1.Y:F3},{c1.Z:F3},"
    //        );

    //        //  D2
    //        sw.WriteLine(
    //            $",,,," +
    //            $"D2,{dia2:F3}," +
    //            $"{carAngle2:F3}," +
    //            $"," +
    //            $"," +
    //            $"{c2.X:F3},{c2.Y:F3},{c2.Z:F3},"
    //        );
    //    }
    //}



    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

}